### ISSUE TITLE
Are CLI flags user friendly?

### ISSUE THREAD

**Issue by zenparsing** [GeoffreyBooth/node-esm-entry-points-proposal#3]
I experimented for a while with a `--module/-m` flag, which made everything nice and explicit, but I found continually having to provide the flag annoying. In usage, I repeatedly forgot the flag and got hit with an error when attempting to run a `.js` ESM file.

Do you think that requiring the users to provide flags is a user-friendly approach? If we're going to give Node the ability to detect the format, then does it help users to have them use the flag?

**Comment by SMotaal** [comment]
Do you think having a recommendations section to disclose tried and tested practices to eliminate user frustration would be useful here?

Personally, I like to create explicit commands in my projects (ie scripts or bins) which are clean, and those currently include `nesm` pointing to the ESM fork and `nexm` pointing to the matching `--experimental-modules --loader …` flagged of the master branch. This is all just for testing without frustration.

I am sure those are baby steps compared to the more refined ways others work. So finding the most friendly ways to make the transition smoother for users and letting them have the ultimate choice is probably a better user experience.

Sounds good?

**Comment by zenparsing** [comment]
I suspect that there are many node users that run `node` directly. It might be a good idea to do some user testing.

**Comment by GeoffreyBooth** [comment]
Node already has [55 command-line flags](https://nodejs.org/api/cli.html), so I think adding one more won’t offend anyone. It’s not a bad thing to provide multiple ways for the user to do something; I see a future for `-m` especially in `npm start` scripts, like `"scripts": { "start": "node -m index.js" }`.

Stage 4 is for user testing, so definitely we’ll revisit all UX concerns then. That’s where I think it would be a good time to bikeshed on names, since all the functionality will have been built, including loaders. I think it’s also worth debating if the `auto` module detection should be enabled by default rather than opt-in via flag, but I think _at least_ it should be opt in via flag unless there’s a technical problem with implementing it.

Do we need to keep this issue open or is it okay to agree that this will be revisited in [Stage 4](https://github.com/nodejs/modules/blob/master/doc/plan-for-new-modules-implementation.md#phase-4)?

**Comment by zenparsing** [comment]
Currently, developers can use the `node` command line to execute scripts in "normal" usage without any of those 55 flags. It's not a question of offending anyone, it's a question of good developer UX. Developers should be able to do "normal" things without flags.

I don't think that we should put UX concerns off until stage 4.

**Comment by GeoffreyBooth** [comment]
Flags aren’t required. This proposal alone lists two ways to execute ESM JavaScript without flags: save the file in a folder with a `package.json` that has an ESM-signifying field like `type` or save the file with an `.mjs` extension. Providing yet another way isn’t bad UX, it’s just providing users with more options.

You can argue that `--type=auto` should be the default behavior, without requiring a flag, but that doesn’t mean we shouldn’t _also_ provide a flag for it. Node provides flags for all sorts of behaviors, and I don’t see why we shouldn’t provide flags for this too. If we want to make `auto` the default behavior that requires opting out of rather than opting into, that’s a discussion worth having, but I’m assuming that for now at least that that doesn’t have consensus. Even if it becomes the default we should still have the flag, just as I’m proposing we have `--type=commonjs`.

**Comment by GeoffreyBooth** [comment]
Since flags aren’t required, can we close this issue? I think we should absolutely have the discussion as to what the default, doesn’t-require-flags behavior should be, but I think that discussion would be more productive once we have an implementation built. It doesn’t need to wait until Stage 4, but I think it would be good to see what the detection algorithm ends up being and how accurate it is and what the edge cases are. It should be very easy to switch which `--type=` variant is the default one that Node chooses if `--type` is left unspecified.

**Comment by GeoffreyBooth** [comment]
Seeing as this seems to be a discussion thread rather than an issue to address in the proposal, I’m going to close this issue; but feel free to continue discussing.

**Comment by evanplaice** [comment]
AFAIK, auto requires module type detection which would be slower than just using the current default. This would be harmful for use cases like CI and servers that load a fresh instance of Node per each request.

The community currently expects CJS by default. That won't change any time soon.

There's always the option to change it to ESM by default in the future but not without a reasonable notification period with  deprecation warnings, etc.
